### ISSUE TITLE
Missing cardholder name in response from .registerCard

### ISSUE THREAD

**Issue by ashleymills** [Judopay/JudoKit-iOS#150]
Hi,

I'm using `JudoKit().invokeTransaction(with: .registerCard, configuration: …, .completion: …)` to register a card, which is working fine. However, I need the cardholder name to be passed into the completion block, but it isn't, even when entered on the form.

How can I get the cardholderName in this case?

Cheers
Ash

**Comment by stefan-tudor** [comment]
hey @ashleymills,

cardholder name is not meant to be exposed to the library user and currently there's no way to receive it in that callback you mentioned.

Best regards
