### ISSUE TITLE
Swift package missing files

### ISSUE THREAD

**Issue by roryprior** [Judopay/JudoKit-iOS#174]
Hey guys can you please make sure your SPM package include all necessary files and compiles in a test project after an update? Every update feels like playing Russian roulette at the moment. The most recent release won't compile as JPPreAuthRequest.h can't be found in JPCardTransaction+Additions.m

**Comment by stefan-tudor** [comment]
Hey @roryprior,
Thank you for reporting this!

Great to see that this package is used via SPM.

The issue described here has been fixed, and the code changes merged into the master branch. Please, till we publish a new package version use master branch or commit `3bf343bb77d88312cf3c4c8fcedda1f6abb214e0`.
