### ISSUE TITLE
"Register card" button is not active with the country by default

### ISSUE THREAD

**Issue by alexeytarasoff** [Judopay/JudoKit-iOS#191]
When registering a card in the billing details, the "Register card" button is not active with the country by default, although all fields are entered correctly. It becomes active if you select a country and enter the postal code again.
Affects versions: Release 3.2.0-3.2.2
<img width="398" alt="issue" src="https://github.com/Judopay/JudoKit-iOS/assets/48827990/3c11ff20-9f09-4150-a1b6-1d671db571b2">

**Comment by stefan-tudor** [comment]
Hi @alexeytarasoff,
Thank you for raising this issue

We're on it!
