### ISSUE TITLE
Privacy manifest

### ISSUE THREAD

**Issue by roryprior** [Judopay/JudoKit-iOS#245]
Hi guys, can you please add a privacy manifest to the Judo SDK to help us comply with the new App Store rules?

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

**Comment by stefan-tudor** [comment]
Hi @roryprior,
Thank you for raising this!

This is at the top of our to-do list with high priority. I will update this thread once it's added to the master branch.

**Comment by roryprior** [comment]
Hey guys, do you have an ETA for the fix here as it's holding up release for us now?

**Comment by stefan-tudor** [comment]
Hey @roryprior,
It is in progress, and we expect a release in the first half of this week.
I apologise for the delay; we had to make more changes than expected due to third-party dependencies.
