### ISSUE TITLE
Which SDK and Documentation

### ISSUE THREAD

**Issue by adamwaite** [Judopay/JudoKit-iOS#97]
You have three SDKs and the documentation is a blend of all of them. I have no idea which to use, and what documentation to follow. Please advise.

- https://github.com/Judopay/JudoKit-iOS (this is the most recently updated on GitHub and the one the documentation says to use - but the API is totally different from the docs)

- https://github.com/Judopay/JudoKitObjC (this was also updated this year, and seems to reflect the documentation's API)

- https://github.com/Judopay/JudoKit (this one is in Swift but we wont get it through Apple because it uses UIWebView)

**Comment by ashleymills** [comment]
@adamwaite I was using JudoKit, updated to JudoKitObjC due to the UIWebView issue, and it looks like I now need to switch to JudoKit-iOS for which there doesn't seem to be any documentation.

Did you manage to resolve this issue yourself?

**Comment by adamwaite** [comment]
Yeah resolved it by switching to Checkout.com
